### ISSUE TITLE
Create rough wireframes for this project

### ISSUE THREAD

**Issue by MadhavBahl** [MadhavBahlMD/my-open-profile#16]
I will be adding few designs for this project soon,

If you have any design ideas, feel free to use this issue as a conversation thread to put forward your ideas

**Comment by aaditkamat** [comment]
I've created a wireframe for the landing page on [Figma](https://www.figma.com/file/AKK6AhNvIyjjW1DPMujTgg/Open-Profile?node-id=0%3A1)

**Comment by MadhavBahl** [comment]
Hi @aaditkamat 

Thanks a lot for the contribution 🤩

I am thinking about some ideas for this project, 

Let me update the repo with some more details the coming weekend, till then I can close this issue, let's see if we can integrate your design with those ideas.

Thanks
