### ISSUE TITLE
Add a Pull Request template

### ISSUE THREAD

**Issue by MadhavBahl** [MadhavBahlMD/my-open-profile#18]
Add a template for PR 

Things to ask user
- [ ] Have you tested your code
- [ ] Does it follow style guides
And so on...

Please feel free to take this up and raise a PR

**Comment by AarambhVerma** [comment]
@MadhavBahlMD Hi Madhav, can I take this issue?

**Comment by MadhavBahl** [comment]
Hey @AarambhVerma 
Sure, go ahead, assigned this issue to you

**Comment by AarambhVerma** [comment]
Hey @MadhavBahlMD, I've generated a pull request, please check that out and tell me for any possible changes!

**Comment by MadhavBahl** [comment]
Thanks for the contribution @AarambhVerma 

#20 fixes this issue
