### ISSUE TITLE
Test all-contributors bot

### ISSUE THREAD

**Issue by MadhavBahl** [MadhavBahlMD/my-open-profile#9]
@all-contributors please add @MadhavBahlMD for code and idea

**Comment by MadhavBahl** [comment]
@all-contributors please add @MadhavBahlMD for code and idea

**Comment by MadhavBahl** [comment]
@all-contributors please add @aaditkamat for enhancement and bug-fix

**Comment by MadhavBahl** [comment]
@all-contributors please add @aaditkamat for enhancement and bug-fix

**Comment by MadhavBahl** [comment]
@all-contributors please add @MadhavBahlMD  for enhancement and bug-fix

**Comment by MadhavBahlMD** [comment]
@all-contributors please add @ajmalsiddiqui for enhancement and bug-fix

(@ajmalsiddiqui please ignore this)

**Comment by MadhavBahl** [comment]
@all-contributors please add @ajmalsiddiqui for idea

(@ajmalsiddiqui please ignore)

**Comment by MadhavBahl** [comment]
@all-contributors please add @MadhavBahlMD for code and idea

**Comment by MadhavBahl** [comment]
Was testing @all-contributors bot,

Please ignore the above mentions
